---
all:
  children:
    lab:
      children:
        iosxe:
          hosts:
            xe1: { ansible_host: 172.30.30.11 }
        iosxr:
          hosts:
            xr1: { ansible_host: 172.30.30.12 }
        nxos:
          hosts:
            nx1: { ansible_host: 172.30.30.13 }
