#!/usr/bin/env python3
"""Render topology/configs/tac_plus.cfg from the SoT + vault.

Syntax: Marc Huber's tac_plus (spawnd + tac_plus blocks), as shipped in lfkeitel/tacacs_plus.
Check without deploying:  make tacacs-check

Users: every automation account from vault `credentials` plus the human accounts in
`tacacs.users`. All get privilege 15 on IOS XE and network-admin on NX-OS.
The file contains secrets: it is git-ignored and readable only by you.
"""
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))
from lab import sot  # noqa: E402

OUT = ROOT / "topology" / "configs" / "tac_plus.cfg"


def q(value: str) -> str:
    return value.replace("\\", "\\\\").replace('"', '\\"')


def main() -> int:
    sec = sot.secrets()
    users: dict[str, str] = {}
    for plat, c in sec["credentials"].items():
        if users.get(c["username"], c["password"]) != c["password"]:
            sys.exit(f"username {c['username']} has different passwords per platform - not supported")
        users[c["username"]] = c["password"]
    users.update(sec["tacacs"]["users"])

    # Syntax: Marc Huber's event-driven tac_plus (used by the lfkeitel/tacacs_plus image):
    # a spawnd block (listener) plus a tac_plus block (hosts, groups, users).
    lines = [
        "# GENERATED by scripts/render_tacacs.py from sot/fabric.yml + secrets/vault.yml - do not commit",
        "id = spawnd {",
        "    listen = { port = 49 }",
        "    background = no",
        "}",
        "",
        "id = tac_plus {",
        "    access log = /var/log/tac_plus.access",
        "    accounting log = /var/log/tac_plus.acct",
        "    authorization log = /var/log/tac_plus.authz",
        "",
        "    host = lab {",
        "        address = 0.0.0.0/0",      # lab only: devices may appear NATed through vrnetlab
        f'        key = "{q(sec["tacacs"]["key"])}"',
        "    }",
        "",
        "    group = netadmin {",
        "        default service = permit",
        "        service = shell {",
        "            default command = permit",
        "            default attribute = permit",
        "            set priv-lvl = 15",                                  # IOS XE: privileged EXEC
        '            optional shell:roles = "\\"network-admin\\""',    # NX-OS role
        '            optional task = "#root-system,#cisco-support"',      # IOS XR task groups (verify)
        "        }",
        "    }",
        "",
    ]
    for user, password in sorted(users.items()):
        lines += [f"    user = {user} {{", f'        password = clear "{q(password)}"',
                  "        member = netadmin", "    }", ""]
    lines.append("}")

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(lines))
    OUT.chmod(0o600)   # secrets: only you (and root in the container) can read it; git-ignored
    print(f"wrote {OUT.relative_to(ROOT)} ({len(users)} users)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
